# Generated by Django 3.2.7 on 2021-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_submission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
