# Generated by Django 3.2.7 on 2021-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_delete_classroomuser'),
        ('accounts', '0004_alter_userclassroom_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classrooms',
            field=models.ManyToManyField(through='accounts.UserClassroom', to='classrooms.Classroom'),
        ),
    ]
